# Generated by Django 4.2.11 on 2024-03-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acts_of_kindness', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actsofkindness',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
