# Generated by Django 4.2.11 on 2024-03-24 11:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/dyoueyepq/image/upload/v1694389081/default_profile_ekdors.jpg', max_length=255, null=True, verbose_name='image'),
        ),
    ]
